name: CMake on multiple platforms

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: lukka/get-cmake@latest

      - name: Setup vcpkg (it does not install any package yet)
        uses: lukka/run-vcpkg@v11


      
