name: CMake on multiple platforms

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Conan
        run: |
          choco install conan -y

      - name: Install dependencies
        run: |
          conan install . --build=missing

      - name: Create build directory
        run: |
          mkdir build
          cd build

      - name: Run CMake
        run: |
          cd build
          cmake .. -G "Visual Studio 16 2019"
          cmake --build . --config Release


          


