name: CMake on multiple platforms

on: workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache vcpkg artifacts
        uses: actions/cache@v2
        with:
          path: |
            ~/vcpkg/installed
            ${{ github.workspace }}/vcpkg
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}

      - name: Install vcpkg
        shell: cmd
        run: |
          git clone https://github.com/microsoft/vcpkg
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            ${{ github.workspace }}\vcpkg\bootstrap-vcpkg.bat
          else
            ${{ github.workspace }}/vcpkg/bootstrap-vcpkg.sh
          fi

      - name: Build
        run: |
          cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
          cmake --build build
