name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: centos:7.9.2009

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Updated GCC and Build Tools
      run: |
        yum install -y centos-release-scl
        yum install -y devtoolset-9-gcc devtoolset-9-gcc-c++ devtoolset-9-binutils
        echo "source /opt/rh/devtoolset-9/enable" >> ~/.bashrc
        source /opt/rh/devtoolset-9/enable
        gcc --version

    - name: Install Build Dependencies
      run: |
        yum update -y
        yum groupinstall -y "Development Tools"
        yum install -y gettext-devel openssl-devel perl-CPAN perl-devel zlib-devel curl-devel expat-devel

    - name: Install Git from Source
      run: |
        cd /usr/src
        curl -L -o git.tar.gz https://www.kernel.org/pub/software/scm/git/git-2.43.0.tar.gz
        tar xzf git.tar.gz
        cd git-2.43.0
        make prefix=/usr/local CFLAGS="-std=c99" all
        make prefix=/usr/local install

    - name: Verify Git Version
      run: |
        git --version

    - name: Install vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh
