name: C++ CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: luizelias/mush3d-centos-7.9

    steps:
    - uses: actions/checkout@v2

    - name: Setup Environment
      run: |
        source /opt/rh/devtoolset-8/enable
        gcc --version
        g++ --version
        echo "PATH=$PATH:/usr/local/bin" >> $GITHUB_ENV

    - name: Verify GCC and CMake Versions
      run: |
        gcc --version
        g++ --version
        cmake --version

    - name: Create Build Directory
      run: mkdir -p build

    - name: Run CMake Configuration
      run: |
        cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=/vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build
      run: cmake --build build

    - name: Test
      run: ./build/YourProject
