name: Docker CI

on:
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    container: 
      image: luizelias/mush3d-centos-7.9

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Enable GCC 8 and Check Version
      run: |
        source /opt/rh/devtoolset-8/enable
        gcc --version
      shell: bash

    - name: Verify Vcpkg Installation
      run: |
        echo "Vcpkg Root: $VCPKG_ROOT"
        /vcpkg/vcpkg version
        /vcpkg/vcpkg list
      shell: bash

    - name: Create Build Directory
      run: mkdir build && cd build

    - name: Run CMake
      run: |
        source /opt/rh/devtoolset-8/enable
        cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++

    - name: Build Project
      run: |
        cd build
        make

    - name: Run Application
      run: |
        cd build
        ./HelloWorld
