name: CMake on multiple platforms

on: workflow_dispatch

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
         with:
          submodules: 'recursive'
      - name: run vcpkg
        uses: lukka/run-vcpkg@v4
        with:
          vcpkgArguments: 'glm'
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
      
