name: CMake on multiple platforms

on: workflow_dispatch

jobs:
  find-vcpkg:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Try to find vcpkg
        run: |
          echo "Checking for vcpkg..."
          VCPKG_PATH=$(where vcpkg)
          if [ -z "$VCPKG_PATH" ]
          then
            echo "vcpkg not found"
          else
            echo "vcpkg found at $VCPKG_PATH"
          fi
