name: Docker CI

on:
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    container: 
      image: luizelias/mush3d-centos-7.9

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Print CMake Version
      run: cmake --version

    - name: Print Vcpkg Root
      run: echo $VCPKG_ROOT
      shell: sh -e {0}
