name: CMake on multiple platforms

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: centos:7.9.2009
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install build tools (Ubuntu)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake g++

      - name: Install Ninja (Ubuntu)
        if: runner.os == 'Linux'
        run: sudo apt-get install -y ninja-build

      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev pkg-config

      - name: Install vcpkg
        shell: pwsh
        run: "${{ github.workspace }}/vcpkg/bootstrap-vcpkg.sh"

      - name: Build
        run: |
          cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
          cmake --build build
