name: CMake on CentOS 7.9

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    container: centos:7.9.2009

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgGitCommitId: '8eb5735'

      - name: Enable EPEL repository and Install tools
        run: |
          yum install -y epel-release
          yum update -y
          yum groupinstall -y "Development Tools"
          yum install -y cmake3

      - name: Install GCC 8
        run: |
          yum install -y centos-release-scl
          yum install -y devtoolset-8-gcc devtoolset-8-gcc-c++
          echo "source /opt/rh/devtoolset-8/enable" >> ~/.bashrc
          source /opt/rh/devtoolset-8/enable

      - name: Build with CMake and vcpkg
        run: |
          cmake3 -B build -S . -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
          cmake3 --build build
