name: CMake on multiple platforms

on: workflow_dispatch


jobs:
  find-vcpkg:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Try to find vcpkg
        run: |
          echo "Checking for vcpkg..."
          $vcpkgPath = Get-Command vcpkg -ErrorAction SilentlyContinue
          if ($null -eq $vcpkgPath) {
            echo "vcpkg not found"
          } else {
            echo "vcpkg found at $($vcpkgPath.Source)"
          }
