name: CMake on multiple platforms

on: workflow_dispatch


jobs:
  find-vcpkg:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup vcpkg
        run: |
          cd C:\vcpkg
          bootstrap-vcpkg.bat
          vcpkg --feature-flags=manifests install --x-manifest-root=${{ github.workspace }}

          


