name: CMake on multiple platforms

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Install vcpkg
        run: git clone https://github.com/microsoft/vcpkg

      - name: Bootstrap vcpkg
        run: ./vcpkg/bootstrap-vcpkg.sh

      #- name: Install dependencies
      #  run: ./vcpkg/vcpkg install <your-dependencies-here>





      
