name: C++ CI Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up GCC (Linux only)
      if: matrix.os == 'ubuntu-latest'
      run: |
        echo "CXX=g++" >> $GITHUB_ENV

    # Add a step to install dependencies if needed.
    # - name: Install dependencies
    #   run: |
    #     # Commands to install dependencies

    - name: Build project
      run: |
        mkdir -p build
        cd build
        cmake ..
        make


