name: C++ CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: luizelias/mush3d-centos-7.9

    steps:
    - uses: actions/checkout@v2

    - name: Setup Environment
      run: |
        source /opt/rh/devtoolset-8/enable
        export PATH=/usr/bin:$PATH
        gcc --version
        g++ --version

    - name: Create Build Directory
      run: mkdir -p build

    - name: Adjust permissions and check working directory
      run: |
        ls -la
        chmod -R 777 build

    - name: Clear CMake Cache
      run: |
        rm -rf build/CMakeCache.txt

    - name: Debug Output
      run: |
        env
        cmake --version
        which cmake
        which gcc
        which g++

    - name: Run CMake Configuration
      run: |
        cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=/vcpkg/scripts/buildsystems/vcpkg.cmake
        cat build/CMakeCache.txt

    - name: Build
      run: cmake --build build

    - name: Test
      run: ./build/YourProject
