name: CMake on multiple platforms

on: workflow_dispatch

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      -name: Print
        run: echo "merda"
      -name: Print2
        run: echo "merda2"
      
