name: Docker CI

on:
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    container: 
      image: luizelias/mush3d-centos-7.9

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Verify CMake Installation
      run: cmake --version

    - name: Verify Vcpkg Installation
      run: |
        echo "Vcpkg Root: $VCPKG_ROOT"
        /path/to/vcpkg/vcpkg version
        /path/to/vcpkg/vcpkg list

    # Add more steps as needed to compile/test code using dependencies
