name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: centos:7.9.2009

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        yum update -y
        yum install -y curl zip unzip tar

    - name: Install Latest Git
      run: |
        yum remove -y git
        yum install -y https://repo.ius.io/ius-release-el7.rpm
        yum install -y git2u

    - name: Verify Git Version
      run: |
        git --version

    - name: Install vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh
