name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: your-dockerhub-username/mush3d-centos-7.9:latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Directory
      run: mkdir build && cd build

    - name: Run CMake
      run: cmake ..

    - name: Build
      run: cmake --build .

    - name: Run
      run: ./hello_world
