name: Debug Workflow
on: [push]
jobs:
  debug-job:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Print a message
      run: echo "Workflow is running!"