name: CMake on multiple platforms

on: workflow_dispatch

jobs:
  windows-build:
    runs-on: centos-latest

    steps:
      - name: print
        run: |
          echo "Hello World"
          echo "Goodbye World"
