name: CMake on CentOS 7.9

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: centos:7.9.2009

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Enable EPEL repository
        run: yum install -y epel-release

      - name: Install build tools (CentOS)
        run: |
          yum update -y
          yum groupinstall -y "Development Tools"
          yum install -y cmake3 make automake gcc gcc-c++ kernel-devel

      - name: Install vcpkg
        run: bash "${{ github.workspace }}/vcpkg/bootstrap-vcpkg.sh"

      - name: Build with CMake and vcpkg
        run: |
          cmake3 -B build -S . -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
          cmake3 --build build
