name: C++ CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: luizelias/mush3d-centos-7.9

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: |
        cmake -B build -S .
        cmake --build build

    - name: Test
      run: |
        ./build/YourProject
