name: C++ CI

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: luizelias/mush3d-centos-7.9

    steps:
    - uses: actions/checkout@v2

    - name: Setup GCC
      run: |
        source /opt/rh/devtoolset-8/enable
        gcc --version
        g++ --version

    - name: Configure CMake
      run: |
        cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=/vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build
      run: |
        cmake --build build

    - name: Test
      run: |
        ./build/YourProject
